// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arch } from "./Arch";
import type { OS } from "./OS";

export type AppInfo = { os: OS, arch: Arch, branch: string, commit_count: string, short_hash: string, commit_time: string, version: string, build_time: string, };
