// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppInfo = {
  os: string,
  arch: string,
  branch: string,
  commit_count: string,
  short_hash: string,
  commit_time: string,
  version: string,
  build_time: string,
};
