// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 出勤状态表
 *
 * 含有全部字段
 */
export type AttendanceStatus = { id: number, name: string, background: string, color: string, remark: string | null, is_deleted: number, deleted_at: number | null, };
