// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 下载进度的通用载体
 *
 * 一份载荷多处复用：download 域每 chunk 的回调参数、state 原子槽
 * （[`crate::state::update::DownloadSlot`]）的写入口与快照、以及 download 通道
 * 的窄进度事件帧——三处的语义都是"瞬时进度"，与持久会话事实（info /
 * severity / artifact）解耦。
 */
export type DownloadProgress = { 
/**
 * 已下载字节数
 */
downloaded: number, 
/**
 * 总字节数（来自 Content-Length，未知时为 None）
 */
total: number | null, };
