// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportPreviewData = { rows: Array<Array<string>>, total_rows: number, total_columns: number, };
