// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Record实体
 *
 * 仅含自增主键 + 业务字段，用于 INSERT
 */
export type Record = { id: bigint | null, student_id: bigint, attendance_status: bigint, remark: string | null, rollcall_at: number, session_id: string, };
