// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RollcallRecord = { id: bigint, student_id: bigint, student_no: string, name: string, attendance_status: number, remark: string | null, rollcall_at: number, session_id: string, };
