// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Student实体
 *
 * 仅含自增主键 + 业务字段，用于 INSERT
 */
export type Student = {
  /**
   * INSERT 时传 None 由 SQLite 自增
   * UPDATE 时传 Some(id)
   */
  id: bigint | null, student_no: string, name: string,
};
