// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudentTable } from "./StudentTable";

export type StudentSingleUpdate = { "type": "Update", "data": StudentTable } | { "type": "Conflict", "data": StudentTable };
