// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Student表
 *
 * 包含全部字段，用于 SELECT 返回给前端
 */
export type StudentTable = { id: bigint, student_no: string, name: string, created_at: number, updated_at: number, is_deleted: number, deleted_at: number | null, };
