// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudentTable } from "./StudentTable";

/**
 * 学生批量创建操作的结果枚举。
 *
 * 该枚举描述了针对多个学生记录执行批量创建操作时，系统处理后的整体结果。
 * 批量操作采用“失败即回滚”的策略，保证数据的一致性。
 *
 * 各变体携带的具体数据不同，调用方应根据变体类型进行相应处理：
 * - 成功类变体（[`Insert`](Self::Insert)、[`Upsert`](Self::Upsert)）携带最终记录列表；
 * - 失败类变体携带错误详情或待处理的记录列表，供调用方排查或重试。
 */
export type StudentBatchCreateResult = { "type": "Insert", "data": Array<StudentTable> } | { "type": "Upsert", "data": Array<StudentTable> } | { "type": "DuplicateInput", "data": Array<string> } | { "type": "DecisionRequired", "data": Array<StudentTable> } | { "type": "Conflict", "data": Array<StudentTable> };
