// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudentTable } from "./StudentTable";

/**
 * 学生单个创建操作的结果枚举。
 *
 * 该枚举描述了针对单个学生记录执行创建操作时，系统根据数据库当前状态
 * 和调用方提供的决策参数，所给出的具体处理结果。
 *
 * 每个变体都包含一个 [`StudentTable`] 对象，代表操作生效后数据库中的最终记录。
 */
export type StudentSingleCreateResult = { "type": "Insert", "data": StudentTable } | { "type": "Restore", "data": StudentTable } | { "type": "Override", "data": StudentTable } | { "type": "Retain", "data": StudentTable } | { "type": "ActiveExists", "data": StudentTable } | { "type": "Conflict", "data": StudentTable };
