// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 展示给用户的更新信息
 */
export type UpdateInfo = { version: string, 
/**
 * releaseNotes
 */
notes: string | null, 
/**
 * publishDate（格式化后的字符串，供前端展示）
 */
date: string | null, };
