// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 更新失败（带载荷的错误枚举，对外视图与后端会话直接携带）
 *
 * 变体身份 = "失败发生在哪一步 / 重试该调哪个命令"，载荷 = 展示文案。
 * 序列化为 `{ "type": "check" | "download" | "install", "message": "..." }`，
 * 前端据 `type` 决定重试按钮对应的命令，`message` 展示。
 */
export type UpdateError = { "type": "check", "message": string } | { "type": "download", "message": string } | { "type": "install", "message": string };
