// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";
import type { UpdateError } from "./UpdateError";
import type { UpdateInfo } from "./UpdateInfo";

/**
 * 对外展示视图：命令返回值与广播的**统一裁剪契约**
 *
 * 每个变体只携带该阶段前端真正需要渲染的字段；凭据（artifact、产物路径等）
 * 一律留在后端会话里，不出现于此。`status` 为 tag、载荷在 `data` 中，
 * 前端 store 对"命令返回"与"广播事件"用同一个类型与同一个 apply 逻辑。
 */
export type UpdateView = { "status": "idle" } | { "status": "checking" } | { "status": "upToDate" } | { "status": "available", "data": { info: UpdateInfo, severity: Severity, } } | { "status": "downloading", "data": { info: UpdateInfo, } } | { "status": "downloaded", "data": { info: UpdateInfo, severity: Severity, } } | { "status": "error", "data": UpdateError };
