// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 出错阶段对应的可恢复操作（前端据此给"重试"按钮）
 */
export type UpdateErrorKind = "check" | "download" | "install";
