// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 当前更新所处的阶段（对外快照的阶段标记）
 *
 * 状态机由后端推进、以快照返回，前端 store 只做镜像。序列化为小写驼峰
 * （`"idle"` / `"checking"` / `"upToDate"` / `"available"` / `"downloading"` /
 * `"downloaded"` / `"error"`），供前端直接消费。
 */
export type UpdateStatus = "idle" | "checking" | "upToDate" | "available" | "downloading" | "downloaded" | "error";
