// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Severity} from "./Severity";
import type {UpdateErrorKind} from "./UpdateErrorKind";
import type {UpdateInfo} from "./UpdateInfo";
import type {UpdateStatus} from "./UpdateStatus";

/**
 * 一次更新检查的对外快照（命令返回 / 前端 store 镜像的统一载体）
 *
 * 后端 `state::update::UpdaterState` 是权威执行状态，内部另持下载凭据
 * （[`Artifact`]、产物路径等，见 [`UpdateSession`]）；本结构只含展示所需的
 * 简单数据，随命令返回值回传，前端据 `status` 渲染、按 `errorKind` 提供重试。
 */
export type UpdateState = {
  /**
   * 当前所处阶段
   */
  status: UpdateStatus,
  /**
   * 目标更新信息（`Available` / `Downloading` / `Downloaded` 等阶段存在）
   */
  info?: UpdateInfo | null,
  /**
   * 严重程度（有更新时才有意义）
   */
  severity: Severity,
  /**
   * 已下载字节数（`Downloading` 阶段，进度条用）
   */
  downloaded?: number,
  /**
   * 总字节数（`Downloading` 阶段）
   */
  total?: number,
  /**
   * 错误消息（`status == Error` 时存在）
   */
  error?: string | null,
  /**
   * 错误来源（前端据此处决定"重试"按钮对应哪个命令）
   */
  errorKind?: UpdateErrorKind | null,
};
