use jiff::tz::TimeZone;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    generate_build_info();
    generate_config_constant();
    tauri_build::build()
}

fn generate_build_info() {
    let branch = get_git_output(&["rev-parse", "--abbrev-ref", "HEAD"]);
    let commit_count = get_git_output(&["rev-list", "--count", "HEAD"]);
    let short_hash = get_git_output(&["rev-parse", "--short", "HEAD"]);
    let commit_time = get_git_output(&["log", "-1", "--format=%cd", "--date=iso-strict"]);
    let build_time = jiff::Timestamp::now().to_zoned(TimeZone::system()).to_string().replace("[Asia/Shanghai]", "");

    println!("cargo:rustc-env=GIT_BRANCH={}", branch);
    println!("cargo:rustc-env=GIT_COMMIT_COUNT={}", commit_count);
    println!("cargo:rustc-env=GIT_SHORT_HASH={}", short_hash);
    println!("cargo:rustc-env=GIT_COMMIT_TIME={}", commit_time);
    println!("cargo:rustc-env=BUILD_TIME={}", build_time);
}

fn get_git_output(args: &[&str]) -> String {
    let output = Command::new("git")
        .args(args)
        .output()
        .expect("failed to execute git");
    String::from_utf8(output.stdout).unwrap().trim().to_string()
}

fn generate_config_constant() {
    // 配置文件路径
    let config_path = Path::new("../resources/develop/config-keys");

    // 读取配置文件
    let content = match fs::read_to_string(config_path) {
        Ok(content) => content,
        Err(e) => {
            println!("cargo:warning=配置文件不存在: {}", config_path.display());
            println!("cargo:warning=当前工作目录是: {}", std::env::current_dir().unwrap().display());
            println!("cargo:warning=错误详情: {}", e);
            return;
        }
    };

    let lines: Vec<&str> = content.lines().collect::<Vec<_>>();

    // 解析配置行
    let mut rs_lines = Vec::with_capacity(lines.len());
    let mut ts_lines = Vec::with_capacity(lines.len());

    for line in lines {
        let line = line.trim();

        if line.is_empty() || line.starts_with('#') || line.starts_with("//") {
            continue;
        }

        let const_name = line.to_uppercase().replace('.', "_").replace('-', "_");

        // Rust 常量
        rs_lines.push(format!("    pub const {const_name}: &str = \"{line}\";"));

        // TypeScript 常量
        ts_lines.push(format!("  {const_name}: \"{line}\" as const,"));
    }

    // 如果没有任何有效配置，提示并返回
    if rs_lines.is_empty() {
        println!("cargo:warning=配置文件中没有有效的配置项");
    }

    // 生成 Rust 文件
    let rs_content = format!(
        "// Automatically generated by build.rs, please do not manually modify.\n\n\
         pub mod config {{\n\
         {}\n\
         }}\n",
        rs_lines.join("\n")
    );

    let us_output = Path::new("./src/common/constant/config.rs");
    if let Err(e) = fs::write(us_output, rs_content) {
        panic!("写入 Rust 文件失败: {} - {}", us_output.display(), e);
    }

    // 生成 TypeScript 文件
    let ts_content = format!(
        "// Automatically generated by build.rs, please do not manually modify.\n\n\
         export const CONFIG = {{\n\
         {}\n\
         }} as const;\n\
         \n\
         export type ConfigKey = keyof typeof CONFIG;\n",
        ts_lines.join("\n")
    );

    let ts_output = Path::new("../frontend/src/lib/constants/config.ts");
    if let Err(e) = fs::write(ts_output, ts_content) {
        panic!("写入 TypeScript 文件失败: {} - {}", ts_output.display(), e);
    }

    println!("cargo:warning=配置文件生成成功!");
    println!("cargo:rerun-if-changed={}", config_path.display());
}
