[package]
name = "rollcaller"
version = "0.1.0-dev"
description = "A feature rich automatic roll-call software"
authors = ["Serene Lee"]
edition = "2021"

[lib]
name = "rollcaller_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
jiff = "0.2"
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1.0"
base64 = "0.23"
calamine = "0.36"
directories = "6.0"
hex = "0.4"
jiff = "0.2"
parking_lot = "0.12"
rand = "0.10"
rbatis = { version = "4.8", features = ["debug_mode"] }
rbs = "4.8"
rbdc-sqlite = { version = "4.9", features = ["sqlite-bundled"] }
reqwest = { version = "0.13", features = ["json"] }
rodio = { version = "0.22", features = ["symphonia-wav"] }
rust_xlsxwriter = "0.98"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.11"
tauri = { version = "2.11", features = ["config-json5", "unstable"] }
tauri-plugin-dialog = "2.7"
tauri-plugin-opener = "2.5"
tauri-plugin-tracing = "0.3"
tauri-plugin-prevent-default = "5.0"
tracing = "0.1"
tracing-appender = "0.2"
tracing-core = "0.1.36"
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["fmt", "json"] }
ts-rs = "12.0"


[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2.4"

[profile.dev]
codegen-units = 256
debug = 1
lto = false
opt-level = 0
