// Automatically generated by build.rs, please do not manually modify.

export const APP_INFO = {
  BRANCH: "feature/feat" as const,
  COMMIT_COUNT: "499" as const,
  SHORT_HASH: "1e4750f" as const,
  COMMIT_TIME: "2026-08-04T22:29:59+08:00" as const,
  BUILD_TIME: "2026-08-04T22:30:10.1107654+08:00" as const,
} as const;

export type AppInfo = keyof typeof APP_INFO;
