from pathlib import Path
from typing import List, Tuple, Optional

from common.logger import log


def read_config_file(config_path: Path) -> Optional[str]:
    """
    读取配置文件内容

    Args:
        config_path: 配置文件路径

    Returns:
        文件内容字符串，如果读取失败返回 None
    """
    if not config_path.exists():
        log("WARNING", f"配置文件不存在: {config_path}")
        log("WARNING", f"当前工作目录是: {Path.cwd()}")
        return None

    try:
        return config_path.read_text(encoding='utf-8')
    except Exception as e:
        log("WARNING", f"读取配置文件失败: {config_path}")
        log("WARNING", f"错误详情: {e}")
        return None


def parse_config_lines(content: str) -> Tuple[List[str], List[str]]:
    """
    解析配置行，生成 Rust 和 TypeScript 常量定义

    Args:
        content: 配置文件内容

    Returns:
        (rust_lines, ts_lines) 元组
    """
    lines = content.splitlines()

    rs_lines = []
    ts_lines = []

    for line in lines:
        line = line.strip()

        # 跳过空行和注释行
        if not line or line.startswith('#') or line.startswith('//'):
            continue

        # 生成常量名：大写，替换 . 和 - 为 _
        const_name = line.upper().replace('.', '_').replace('-', '_')

        # Rust 常量
        rs_lines.append(f'    pub const {const_name}: &str = "{line}";')

        # TypeScript 常量
        ts_lines.append(f'  {const_name}: "{line}" as const,')

    return rs_lines, ts_lines


def generate_rs_content(rs_lines: List[str]) -> str:
    """
    生成 Rust 文件内容

    Args:
        rs_lines: Rust 常量定义行列表

    Returns:
        Rust 文件完整内容
    """
    return f"""// Automatically generated by build.rs, please do not manually modify.

{chr(10).join(rs_lines)}

"""


def generate_ts_content(ts_lines: List[str]) -> str:
    """
    生成 TypeScript 文件内容

    Args:
        ts_lines: TypeScript 常量定义行列表

    Returns:
        TypeScript 文件完整内容
    """
    return f"""// Automatically generated by build.rs, please do not manually modify.

export const APP_CONFIG_KEYS = {{
{chr(10).join(ts_lines)}
}} as const;

export type AppConfigKeys = keyof typeof APP_CONFIG_KEYS;
"""


def write_rs_file(output_path: Path, content: str) -> None:
    """
    写入 Rust 文件

    Args:
        output_path: 输出文件路径
        content: 文件内容

    Raises:
        RuntimeError: 写入失败时抛出
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        output_path.write_text(content, encoding='utf-8')
    except Exception as e:
        raise RuntimeError(f"写入 Rust 文件失败: {output_path} - {e}")


def write_ts_file(output_path: Path, content: str) -> None:
    """
    写入 TypeScript 文件

    Args:
        output_path: 输出文件路径
        content: 文件内容

    Raises:
        RuntimeError: 写入失败时抛出
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        output_path.write_text(content, encoding='utf-8')
    except Exception as e:
        raise RuntimeError(f"写入 TypeScript 文件失败: {output_path} - {e}")


def generate_config_constant(
    config_path: Optional[Path] = None,
    rs_output_path: Optional[Path] = None,
    ts_output_path: Optional[Path] = None
) -> bool:
    """
    主函数：从配置文件生成 Rust 和 TypeScript 常量定义

    Args:
        config_path: 配置文件路径，默认为resources/develop/config.key
        rs_output_path: Rust 输出路径，默认为 backend/src/common/constant/config.rs
        ts_output_path: TypeScript 输出路径，默认为 frontend/src/lib/constants/config.ts

    Returns:
        bool: 成功返回 True，失败返回 False
    """
    # 设置默认路径（相对于项目根目录）
    if config_path is None:
        config_path = Path("resources/develop/config.key")

    if rs_output_path is None:
        rs_output_path = Path("backend/src/common/constant/app_config_keys.rs")

    if ts_output_path is None:
        ts_output_path = Path("frontend/src/lib/constants/AppConfigKeys.ts")

    content = read_config_file(config_path)
    if content is None:
        return False

    rs_lines, ts_lines = parse_config_lines(content)

    rs_content = generate_rs_content(rs_lines)
    ts_content = generate_ts_content(ts_lines)

    try:
        write_rs_file(rs_output_path, rs_content)
        write_ts_file(ts_output_path, ts_content)
    except RuntimeError as e:
        log("ERROR", str(e))
        return False

    if not rs_lines:
        log("WARNING", "配置文件中没有有效的配置项，已清空所有常量")
        return True

    log("INFO", "配置文件生成成功!")
    return True


def main():
    """命令行入口"""
    success = generate_config_constant()
    if not success:
        exit(1)


if __name__ == "__main__":
    main()
